/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeriaoo;

import Controladores.Ingrediente_Controller;
import Vistas.GestionBD;
import Utils.ConexionDB4O;
import Modelo.Ingrediente;
import static Utils.ConexionDB4O.bd;
import com.db4o.ObjectSet;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class GestionIngredientes extends JDialog {
    
    public GestionIngredientes() {
        initComponents();
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbGestionIngredientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIngredientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btEliminar = new javax.swing.JButton();
        btAñadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Ingredientes");
        setBackground(new java.awt.Color(102, 102, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.LINE_START);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, java.awt.BorderLayout.LINE_END);

        lbGestionIngredientes.setBackground(new java.awt.Color(255, 255, 255));
        lbGestionIngredientes.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 24)); // NOI18N
        lbGestionIngredientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGestionIngredientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\282947183020211(1).png")); // NOI18N
        lbGestionIngredientes.setText("GESTION DE INGREDIENTES");
        lbGestionIngredientes.setFocusable(false);
        lbGestionIngredientes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lbGestionIngredientes.setOpaque(true);
        lbGestionIngredientes.setPreferredSize(new java.awt.Dimension(34, 80));
        getContentPane().add(lbGestionIngredientes, java.awt.BorderLayout.PAGE_START);

        tbIngredientes.setBackground(new java.awt.Color(102, 102, 255));
        tbIngredientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true));
        tbIngredientes.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 14)); // NOI18N
        tbIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_ingredientes", "Ingredientes", "Precio", "Comentarios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbIngredientes.setGridColor(new java.awt.Color(0, 0, 0));
        tbIngredientes.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tbIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbIngredientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbIngredientes);
        if (tbIngredientes.getColumnModel().getColumnCount() > 0) {
            tbIngredientes.getColumnModel().getColumn(0).setMinWidth(0);
            tbIngredientes.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbIngredientes.getColumnModel().getColumn(0).setMaxWidth(0);
        }
        tbIngredientes.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(532, 50));

        btEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btEliminar.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 11)); // NOI18N
        btEliminar.setText("Eliminar");
        btEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        btEliminar.setPreferredSize(new java.awt.Dimension(70, 25));
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btEliminar);

        btAñadir.setBackground(new java.awt.Color(255, 255, 255));
        btAñadir.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 11)); // NOI18N
        btAñadir.setText("Añadir");
        btAñadir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        btAñadir.setPreferredSize(new java.awt.Dimension(70, 25));
        btAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btAñadir);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
        CargarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void btAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAñadirActionPerformed
        NuevoIngrediente Ventanahija = new NuevoIngrediente();
        Ventanahija.setVisible(true);
        
        CargarTabla();
    }//GEN-LAST:event_btAñadirActionPerformed
    
    /**
     * 
     * @param evt 
     */
    private void tbIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbIngredientesMouseClicked
    
        
    }//GEN-LAST:event_tbIngredientesMouseClicked

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
       
        
    }//GEN-LAST:event_btEliminarActionPerformed
    
    /**
     * 
     */
    private void CargarTabla() {
        
        try {
            
            Ingrediente_Controller ingC = new Ingrediente_Controller();
            
            
            //Especificamos el tipo derivado para poder acceder a los diferentes atributos
            //Devuelve todos los ingredientes que tengamos guardados que tengan codigo BE           
            ObjectSet<Ingrediente> os = ingC.getListado();
            
            DefaultTableModel datos = (DefaultTableModel) tbIngredientes.getModel();
            
            datos.setRowCount(0);
            
            for (Ingrediente i: os) {
                try{
                    ArrayList<String> Fila = new ArrayList<String>();
                    Fila.add(i.codigo);
                    Fila.add(i.nombre);
                    Fila.add(String.valueOf(i.precio));
                    Fila.add(i.comentarios);
                    datos.addRow(Fila.toArray());
                }catch(Exception e){
                    
                }
              
            }
           
        } catch (Exception ex) {
            Logger.getLogger(App_Launcher.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionIngredientes().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAñadir;
    private javax.swing.JButton btEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGestionIngredientes;
    private javax.swing.JTable tbIngredientes;
    // End of variables declaration//GEN-END:variables
}
