 package pizzeriaoo;

import Controladores.Ingrediente_Controller;
import Utils.ConexionDB4O;
import Modelo.Ingrediente;
import com.db4o.ObjectSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class NuevoIngrediente extends JDialog {

    public boolean EditMode = false;
    public int idIngrediente = -1;

    public NuevoIngrediente() {
        initComponents();
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfPrecio = new javax.swing.JTextField();
        tfComentarios = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btConfirmar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NUEVO INGREDIENTE");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\d6nihel-66c70dba-e292-40d3-9692-596f99828a81.png")); // NOI18N
        jLabel4.setText("NUEVO INGREDIENTE");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 350, 80));

        jLabel1.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 14)); // NOI18N
        jLabel1.setText("NOMBRE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        tfNombre.setBackground(new java.awt.Color(0, 0, 0));
        tfNombre.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 12)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(255, 255, 255));
        tfNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jPanel1.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 320, 30));

        tfPrecio.setBackground(new java.awt.Color(0, 0, 0));
        tfPrecio.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 12)); // NOI18N
        tfPrecio.setForeground(new java.awt.Color(255, 255, 255));
        tfPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jPanel1.add(tfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 320, 30));

        tfComentarios.setBackground(new java.awt.Color(0, 0, 0));
        tfComentarios.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 12)); // NOI18N
        tfComentarios.setForeground(new java.awt.Color(255, 255, 255));
        tfComentarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jPanel1.add(tfComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 320, 30));

        jLabel2.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 14)); // NOI18N
        jLabel2.setText("PRECIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 14)); // NOI18N
        jLabel3.setText("COMENTARIOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        btConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        btConfirmar.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 11)); // NOI18N
        btConfirmar.setText("Confirmar");
        btConfirmar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        btConfirmar.setPreferredSize(new java.awt.Dimension(70, 25));
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 80, 30));

        btCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btCancelar.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 11)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        jPanel1.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 80, 30));

        jLabel5.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 14)); // NOI18N
        jLabel5.setText("CODIGO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        tfCodigo.setBackground(new java.awt.Color(0, 0, 0));
        tfCodigo.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 12)); // NOI18N
        tfCodigo.setForeground(new java.awt.Color(255, 255, 255));
        tfCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        jPanel1.add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
     
      Ingrediente_Controller p = new Ingrediente_Controller();
      p.AniadirIngrediente();
        
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        setLocation(580, 280);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoIngrediente().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField tfCodigo;
    public javax.swing.JTextField tfComentarios;
    public javax.swing.JTextField tfNombre;
    public javax.swing.JTextField tfPrecio;
    // End of variables declaration//GEN-END:variables
}
