/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.GestionBD_Controller;
import Utils.ConexionDB4O;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Usuario
 */
public class GestionBD extends JDialog {

    public String rutaBD;

    public GestionBD() {
        initComponents();
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btTest = new javax.swing.JButton();
        jTFruta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(469, 354));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION BBDD");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 469, 54));

        btTest.setBackground(new java.awt.Color(204, 204, 255));
        btTest.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 18)); // NOI18N
        btTest.setText("TEST");
        btTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTestActionPerformed(evt);
            }
        });
        getContentPane().add(btTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 132, 64));

        jTFruta.setEditable(false);
        getContentPane().add(jTFruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 250, -1));

        jLabel2.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 12)); // NOI18N
        jLabel2.setText("Ruta de la base de datos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        btBuscar.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 11)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 165, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTestActionPerformed
        testBD();
    }//GEN-LAST:event_btTestActionPerformed

    //
    private void testBD() {
        try {
            GestionBD_Controller Controller = new GestionBD_Controller();
            if (Controller.ComprobarBasedeDatos()) {
                JOptionPane.showMessageDialog(null, "Conexion exitosa con la BBDD", "Exito", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido conectar con la BBDD", "Muy Mal", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        buscarFichero();
    }//GEN-LAST:event_btBuscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocation(580, 280);
    }//GEN-LAST:event_formWindowOpened

    private void buscarFichero() {

        String filePath = new File("").getAbsolutePath();

        String Ruta = filePath.concat("\\datos\\baseDatos.pizza");
        JFileChooser fileChooser = new JFileChooser();

        //Archivo seleccionado por defecto en el dialogo
        fileChooser.setSelectedFile(new File("\\datos\\baseDatos.pizza"));

        //Titulo de la ventana
        fileChooser.setDialogTitle("Seleccione una base de datos");

        //Filtro de extension del archivo
        FileFilter[] filtro = fileChooser.getChoosableFileFilters();
        for (FileFilter f : filtro) {
            fileChooser.removeChoosableFileFilter(f);
        }

        FileFilter filter = new FileNameExtensionFilter("Pizzerias", "pizza");
        fileChooser.addChoosableFileFilter(filter);

        //mostrar el dialogo de abrir el archivo
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            rutaBD = fileChooser.getSelectedFile().getAbsolutePath();
            jTFruta.setText(rutaBD);
        }
        
        GestionBD_Controller Controller = new GestionBD_Controller();
        Controller.CambiarRutaBD(jTFruta.getText());
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTFruta;
    // End of variables declaration//GEN-END:variables
}
